server:
  port: 8080
  servlet:
    context-path: /demo
  jetty:
    acceptors: -1 # 接收线程数，默认-1，根据运行环境派生
    selectors: -1 # 选择器线程数，默认-1，根据运行环境派生
    max-http-post-size: 1048576 # post请求最大字节数，单位byte
    accesslog:
      enabled: true # 开启访问日志，默认false
      filename: E:/IdeaProjects/logs/jetty_access_yyyy_mm_dd.log # 日志文件名，yyyy_MM_dd是日期格式占位符，最终会被file-date-format配置的格式代替
      file-date-format: yyyy_MM_dd # 日志文件日期格式
      retention-period: 31 # 日志保留天数，默认31
      append: true # 追加日志，默认false，重启后旧日志另存，重新创建新日志
      extended-format: true # 启用扩展NCSA格式，默认false
      date-format: yyyy-MMM-dd HH:mm:ss.SSS # 日志内容时间格式，默认dd/MMM/yyyy:HH:mm:ss Z
      locale: zh_CN # 日志语言
      time-zone: GMT+8 # 时区，默认GMT
      log-cookies: true # 记录cookie，默认false
      log-server: true # 记录主机名，默认false
      log-latency: true # 记录请求处理时间，默认false

# 运行日志
logging:
  config: classpath:logback.xml

spring:
  devtools:
    restart:
      enabled: true # 热部署
      additional-paths: src/main/java # 设置重启的目录
  thymeleaf:
    cache: false # 禁用thymeleaf缓存

  servlet:
    multipart:
      max-file-size: 50MB # 单个文件的最大值
      max-request-size: 200MB # 多个文件的总大小

  # 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    druid:
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 10  # 最大
      max-wait: 60000  # 连接超时时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: SELECT 'x'
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      connection-properties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123

  # redis sentinel
  redis:
    host: localhost # 默认localhost
    port: 6379 # 默认6379
#    password: couga # 密码
    database: 5 # 采用哪个数据库，默认0
    timeout: 500 # 连接超时时间（毫秒）
    # 使用sentinel集群时将以下三行注释打开
#    sentinel:
#      master: cougamaster # master名称
#      nodes: ceshi:26379,ceshi:26380,ceshi:26381 # sentinel地址
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 8 # 连接池最大连接数,默认8个，（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接

  # spring cache
  cache:
    type: redis
    redis:
      use-key-prefix: true # key使用前缀，默认ture
      key-prefix: demo # key前缀
      cache-null-values: false # 缓存为null的value，默认true
      time-to-live: 30m # 缓存有效时间

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml # mapper文件路径
  type-aliases-package: com.example.model # 实体扫描，多个package用逗号或者分号分隔
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名
    cache-enabled: false # 是否开启缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql日志
  global-config:
    db-config:
      db-type: mysql # 数据库类型
      id-type: auto # 主键自增
      field-strategy: not_empty  # 非空判断
      table-underline: true # 表名是否使用下划线命名，默认数据库表使用下划线命名
      table-prefix: t_ # 表名前缀
      capital-mode: true # 是否开启大写命名，默认不开启
      logic-delete-value: 1 # 逻辑已删除值，逻辑删除下有效
      logic-not-delete-value: 0 # 逻辑未删除值，逻辑删除下有效
      column-like: false # 是否开启LIKE查询，即根据entity自动生成的where条件中String类型字段是否使用LIKE，默认不开启

attachment:
  save-dir: E:/IdeaProjects/file # 文件保存路径
  address-prefix: /demofile # 文件访问前缀
  file-separator: / # 文件路径分隔符

token:
  expire-seconds: 7200 # token过期时间（秒）
  jwt-secret: SPRING-BOOT-DEMO # jwt密钥

swagger2:
  enable: true # 启用swagger2

resource:
  type:
    http: http # 资源类型：http
    websocket: websocket # 资源类型：websocket